<a href="https://colab.research.google.com/github/ilhamibrahim-id/PCVK_Genap_2022/blob/main/Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# PERKALIAN MATRIKS

matriksA = np.array([[1,2],
                     [2,1]])
matriksB = np.array([[2,2],
                     [1,1]])   

perkalian_biasa = matriksA*matriksB

print("Matriks A :")
print(matriksA)

print("Matriks B :")
print(matriksB)

print("Perkalian Matriks : ")
print(perkalian_biasa)

Matriks A :
[[1 2]
 [2 1]]
Matriks B :
[[2 2]
 [1 1]]
Perkalian Matriks : 
[[2 4]
 [2 1]]


In [2]:
import numpy as np

# PERKALIAN MATRIKS SKALAR

matriksA = np.array([[1,2],
                     [2,1]])
k = 2
perkalian_biasa = matriksA*k

print("Matriks A :")
print(matriksA)

print("k :" , k)

print("Perkalian Matriks : ")
print(perkalian_biasa)


Matriks A :
[[1 2]
 [2 1]]
k : 2
Perkalian Matriks : 
[[2 4]
 [4 2]]


In [4]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
import matplotlib.image as image
import numpy as np
img=image.imread('/content/drive/MyDrive/Noise/galaxy.jpg')
print("Matriks : ")
print(img)

Matriks : 
[[[1 0 8]
  [1 0 8]
  [1 0 8]
  ...
  [1 0 5]
  [1 0 5]
  [1 0 5]]

 [[1 0 8]
  [1 0 8]
  [1 0 8]
  ...
  [1 0 5]
  [1 0 5]
  [1 0 5]]

 [[1 0 8]
  [1 0 8]
  [1 0 8]
  ...
  [1 0 5]
  [1 0 5]
  [1 0 5]]

 ...

 [[1 0 5]
  [1 0 5]
  [1 0 5]
  ...
  [1 0 5]
  [1 0 5]
  [1 0 5]]

 [[1 0 5]
  [1 0 5]
  [1 0 5]
  ...
  [1 0 5]
  [1 0 5]
  [1 0 5]]

 [[1 0 5]
  [1 0 5]
  [1 0 5]
  ...
  [1 0 5]
  [1 0 5]
  [1 0 5]]]
